/**
 * Rehype plugin: transforms standard markdown footnotes into Tufte-style sidenotes.
 *
 * Markdown input:
 *   Some text with a sidenote.[^1]
 *   [^1]: This appears in the margin.
 *
 * Output: inline sidenote markup that floats into the right margin on wide screens.
 */

import type { Root, Element, Text } from 'hast';
import { visit } from 'unist-util-visit';
import { toText } from 'hast-util-to-text';

export default function rehypeSidenotes() {
  return (tree: Root) => {
    // Collect footnote definitions from the footnote section
    const footnotes = new Map<string, Element>();

    // Find the footnote section (generated by remark-gfm)
    visit(tree, 'element', (node, index, parent) => {
      if (
        node.tagName === 'section' &&
        node.properties?.dataFootnotes !== undefined
      ) {
        // Extract each footnote <li>
        visit(node, 'element', (li) => {
          if (li.tagName === 'li' && typeof li.properties?.id === 'string') {
            const id = li.properties.id.replace('user-content-fn-', '');
            footnotes.set(id, li);
          }
        });

        // Remove the footnote section from the tree
        if (parent && typeof index === 'number') {
          parent.children.splice(index, 1);
          return index; // revisit this index
        }
      }
    });

    if (footnotes.size === 0) return;

    // Replace footnote references with inline sidenotes
    let counter = 0;
    visit(tree, 'element', (node, index, parent) => {
      if (
        node.tagName === 'sup' &&
        node.children.length > 0
      ) {
        // Check if this is a footnote reference link
        const link = node.children.find(
          (c): c is Element => c.type === 'element' && c.tagName === 'a'
        );

        if (!link) return;

        const href = String(link.properties?.href || '');
        const match = href.match(/#user-content-fn-(.+)/);
        if (!match) return;

        const id = match[1];
        const footnote = footnotes.get(id);
        if (!footnote) return;

        counter++;

        // Extract footnote content (skip the backref link)
        const contentChildren = extractFootnoteContent(footnote);

        // Build the sidenote markup
        const sidenote: Element = {
          type: 'element',
          tagName: 'span',
          properties: { className: ['sidenote-wrapper'] },
          children: [
            {
              type: 'element',
              tagName: 'label',
              properties: {
                className: ['sidenote-toggle', 'sidenote-number'],
              },
              children: [],
            },
            {
              type: 'element',
              tagName: 'span',
              properties: { className: ['sidenote'] },
              children: contentChildren,
            },
          ],
        };

        // Replace the <sup> with the sidenote
        if (parent && typeof index === 'number') {
          parent.children[index] = sidenote;
        }
      }
    });
  };
}

/**
 * Extract the text content from a footnote <li>, removing backref links
 * and unwrapping single-paragraph content.
 */
function extractFootnoteContent(li: Element): (Element | Text)[] {
  const result: (Element | Text)[] = [];

  for (const child of li.children) {
    if (child.type === 'element') {
      if (child.tagName === 'p') {
        // Unwrap paragraph, filter out backref links
        const filtered = child.children.filter((c) => {
          if (c.type === 'element' && c.tagName === 'a') {
            const className = c.properties?.className;
            if (Array.isArray(className) && className.some((cls) =>
              String(cls).includes('footnote-backref') || String(cls).includes('data-footnote-backref')
            )) {
              return false;
            }
            const role = c.properties?.dataFootnoteBackref;
            if (role !== undefined) return false;
          }
          return true;
        });
        result.push(...(filtered as (Element | Text)[]));
      } else {
        result.push(child);
      }
    } else if (child.type === 'text') {
      result.push(child);
    }
  }

  return result;
}
